name: Multi Env
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy_QA:

    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4

    - name: Add SSH Key
      run: |
        # echo "${{ secrets.SSH_PEM_KEY }}" > deploy_key.pem
        echo "${{ secrets.SSH_PEM_KEY }}" 
        
    # chmod 600 deploy_key.pem
    # - name: Run deployment script over SSH
    #   uses: appleboy/ssh-action@master
    #   with:
    #         host: ${{ secrets.SERVER_ADDRESS }}
    #         username: ${{ secrets.SERVER_USER }}
    #         key_path: deploy_key.pem
    #         script_stop: true
    #         script: |
    #           ls /mnt
 

    
        

  # deploy_STG:
  #   runs-on: ubuntu-latest
  #   environment: STG
  #   steps:
  #   - uses: actions/checkout@v4

  # deploy_PROD:
  #   runs-on: ubuntu-latest
  #   environment: PROD
  #   steps:
  #   - uses: actions/checkout@v4
      
    
     
