name: Multi Env
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy_QA:

    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4

    - name: Add SSH Key
      run: |
        echo "wzh" 
         
        
   
     
