name: Multi Env
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy_QA:

    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "test.go"
          REMOTE_HOST: 47.121.131.21
          REMOTE_USER: root
          TARGET: /mnt/test.go
          SCRIPT_AFTER: |
            ls /mnt
        

  deploy_STG:
    runs-on: ubuntu-latest
    environment: STG
    steps:
    - uses: actions/checkout@v4

  deploy_PROD:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v4
      
    
     
