name: Multi Env
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy_QA:

    runs-on: ubuntu-latest
    environment: QA
    steps:
    - uses: actions/checkout@v4

  deploy_STG:
    runs-on: ubuntu-latest
    environment: STG
    steps:
    - uses: actions/checkout@v4

  deploy_PROD:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v4
      
    
     
